dqn:
  learning_rate: 0.01
  mini_batch_size: 64
  num_iterations: 10000
  envs_num: 10
  runs_num: 10
  steps_num_per_run: 1000
  tb_path: "/tmp/rl_application/dqn_cartpole_integration_test"
ddqn:
  learning_rate: 0.01
  mini_batch_size: 64
  num_iterations: 10000
  envs_num: 10
  runs_num: 10
  steps_num_per_run: 1000
  tb_path: "/tmp/rl_application/ddqn_cartpole_integration_test"
ddpg:
  learning_rate: 0.001
  mini_batch_size: 64
  num_iterations: 2000
  envs_num: 60
  runs_num: 12
  steps_num_per_run: 800
  tb_path: "/tmp/rl_application/ddpg_mountaincar_integration_test"